import {
  BarChart2,
  Users,
  Clock,
  DoorClosed,
  Settings,
  Building2,
  Briefcase,
  Calendar,
  Fingerprint,
  UserCheck,
  FileText,
  Mail,
  Utensils,
} from "lucide-react";
import { MenuItem } from "../types";

export const menuItems: MenuItem[] = [
  {
    id: "dashboard",
    label: "Panel de Monitoreo",
    icon: BarChart2,
    path: "/dashboard",
    modulePermission: "panel_monitoreo",
  },
  {
    id: "employees",
    label: "Empleados",
    icon: Users,
    path: "/employees",
    modulePermission: "empleados",
    children: [
      {
        id: "employee-management",
        label: "Gestión de Empleados",
        icon: UserCheck,
        path: "/employees/management",
        modulePermission: "gestion_empleados",
      },
    ],
  },
  {
    id: "time-control",
    label: "Control de Tiempo",
    icon: Clock,
    path: "/time-control",
    modulePermission: "control_tiempo",
    children: [
      {
        id: "schedule-assignment",
        label: "Planificador de horarios",
        icon: Clock,
        path: "/employees/schedule",
        modulePermission: "planificador_horarios",
      },
      {
        id: "incidencias",
        label: "Gestión de Incidencias",
        icon: Fingerprint,
        path: "/employees/incidencias",
        modulePermission: "gestion_incidencias",
      },
      {
        id: "calendar",
        label: "Calendario",
        icon: Calendar,
        path: "/employees/calendar",
        modulePermission: "calendario",
      },
    ],
  },
  {
    id: "access-control",
    label: "Control de Acceso",
    icon: DoorClosed,
    path: "/access",
    modulePermission: "control_acceso",
    children: [
      {
        id: "visitors",
        label: "Visitantes",
        icon: Users,
        path: "/access/visitors",
        modulePermission: "visitantes",
      },
      {
        id: "access-permissions",
        label: "Permisos de Acceso",
        icon: UserCheck,
        path: "/access/permissions",
        modulePermission: "permisos_acceso",
      },
    ],
  },
  {
    id: "diner",
    label: "Comedor",
    icon: Utensils,
    path: "/system-config/diner",
    modulePermission: "comedor",
  },
  {
    id: "reports",
    label: "Reportes",
    icon: BarChart2,
    path: "/reports",
    modulePermission: "reportes",
    children: [
      {
        id: "attendance-reports",
        label: "Reportes más usados",
        icon: Clock,
        path: "/reports/attendance",
        modulePermission: "reportes_mas_usados",
      },
    ],
  },
  {
    id: "administration",
    label: "Administración",
    icon: Settings,
    path: "/administration",
    modulePermission: "administracion",
    children: [
      // Hemos removido "Gestión de Licencias" como solicitado
      {
        id: "users",
        label: "Usuarios",
        icon: UserCheck,
        path: "/administration/users",
        modulePermission: "usuarios",
      },
      {
        id: "perfil",
        label: "Perfiles",
        icon: Users,
        path: "/administration/perfil",
        modulePermission: "perfiles",
      },
    ],
  },
  {
    id: "system-config",
    label: "Configuración del Sistema",
    icon: Settings,
    path: "/system-config",
    modulePermission: "configuracion_sistema",
    children: [
      {
        id: "companies",
        label: "Compañías",
        icon: Building2,
        path: "/system-config/structure",
        modulePermission: "companias",
      },
      {
        id: "devices",
        label: "Dispositivos",
        icon: Fingerprint,
        path: "/system-config/devices",
        modulePermission: "dispositivos",
      },
      {
        id: "employee-types",
        label: "Tipos de Empleados",
        icon: UserCheck,
        path: "/system-config/employee-types",
        modulePermission: "tipos_empleados",
      },
      {
        id: "positions",
        label: "Tipos de Acceso",
        icon: Briefcase,
        path: "/system-config/positions",
        modulePermission: "tipos_acceso",
      },
      {
        id: "email",
        label: "Correo electrónico",
        icon: Mail,
        path: "/system-config/email",
        modulePermission: "correo_electronico",
      },
      {
        id: "general-config",
        label: "Configuración General",
        icon: Settings,
        path: "/administration/config",
        modulePermission: "configuracion_general",
      },
      {
        id: "check-profiles",
        label: "Perfiles de Marcaje",
        icon: Clock,
        path: "/employees/check-profiles",
        modulePermission: "perfiles_marcaje",
      },
      {
        id: "geocerca",
        label: "Geocerca",
        icon: Clock,
        path: "/employees/geocerca",
        modulePermission: "geocerca",
      },
      {
        id: "contracts",
        label: "Modalidad De Tiempo",
        icon: FileText,
        path: "/system-config/contracts",
        modulePermission: "modalidad_tiempo",
      },
      {
        id: "modality",
        label: "Turnos de Trabajo",
        icon: FileText,
        path: "/system-config/modality",
        modulePermission: "turnos_trabajo",
      },
    ],
  },
];
